// Enum для экранов
export enum ScreenType {
	SET_NAME_SCREEN = 'SET_NAME_SCREEN',
	GAME_LOBBY_WAIT_PLAYERS_SCREEN = 'GAME_LOBBY_WAIT_PLAYERS_SCREEN',
	TIMER_SCREEN = 'TIMER_SCREEN',
	QUESTION_SCREEN = 'QUESTION_SCREEN',
	QUESTION_WAIT_OTHER_SCREEN = 'QUESTION_WAIT_OTHER_SCREEN',
	VOTE_SCREEN = 'VOTE_SCREEN',
}
