// Enum для действий WebSocket
export enum WebSocketAction {
	SET_SCREEN = 'SET_SCREEN',
	PLAYER_ID = 'PLAYER_ID',
	JOIN_ROOM = 'JOIN_ROOM',
	START_GAME = 'START_GAME',
	CREATE_ROOM = 'CREATE_ROOM',
	SET_NAME = 'SET_NAME',
	CURRENT_ROOM = 'CURRENT_ROOM',
	PLAYERS_LIST = 'PLAYERS_LIST',
	TIMER_TIME = 'TIMER_TIME',
	SET_QUESTION = 'SET_QUESTION',
	ANSWER_QUESTION = 'ANSWER_QUESTION',
	VOTE_STAGE = 'VOTE_STAGE',
}
