import type { Metadata } from 'next'
import './globals.css'
// app/layout.js или app/layout.tsx
import clsx from 'clsx'
import { Geologica } from 'next/font/google'

// Настройка шрифта
const geologica = Geologica({
	weight: ['100', '300', '400', '500', '700', '900'],
	subsets: ['latin', 'cyrillic'],
	display: 'swap',
	variable: '--font-geologica',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={clsx(geologica.className, geologica.variable)}>
				{children}
			</body>
		</html>
	)
}
